name: universe_rental
description: "A new Flutter project."



publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get:
  shared_preferences:
  flutter_native_splash:
  google_fonts:
  cached_network_image:
  pinput:
  flutter_statusbarcolor_ns:
  rounded_loading_button:
  flutter_tabler_icons: ^1.25.0
  intl:
  shorebird_code_push: ^1.1.3
  screenshot: ^2.1.0
  share_plus: ^7.2.1
  path_provider:
  shimmer: ^3.0.0
  url_launcher:
  flutter_svg: ^2.0.9
  dio:
  flutter_map:
  latlong2:
  geolocator: ^11.0.0
  permission_handler: ^11.0.1
  flutter_html: ^3.0.0-beta.2
  table_calendar: ^3.1.0
  image_picker: ^1.0.7
  backdrop: ^0.9.1
  glassmorphism_ui: ^0.3.0
  anchor_scroll_controller: ^0.4.4
  carousel_slider: ^4.2.1
#  vector_map_tiles: ^6.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/dummy_images/
    - assets/
    

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/w500.ttf
          weight: 500
        - asset: assets/fonts/nunito/w600.ttf
          weight: 600
        - asset: assets/fonts/nunito/w700.ttf
          weight: 700
        - asset: assets/fonts/nunito/w800.ttf
          weight: 800
        - asset: assets/fonts/nunito/w900.ttf
          weight: 900

#dart run flutter_native_splash:create
flutter_native_splash:

  #  color: "#ffffff"
  background_image: "assets/images/launch_screen.png"
  #  image: assets/images/logo.png
  android_12:
    icon_background_color: 000000